backend:
  name: git-gateway
  branch: main
  identity_url: "https://blog.janapodgajewska.com/.netlify/identity"
  git_gateway_url: "https://blog.janapodgajewska.com/.netlify/git"

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
